language: ruby
cache:
  - bundler
  - directories:
    - $HOME/librarian-puppet
gemfile: puppet/Gemfile
env: LIBRARIAN_PUPPET_TMP="$HOME/librarian-puppet"

before_script:
  # All our build steps and tests are for Puppet at the moment
  - cd puppet

# `bundle install` and `bundle exec rake` run automatically by Travis
