language: ruby
cache: bundler
gemfile: puppet/Gemfile

before_install:
  # All our build steps and tests are for Puppet at the moment
  - cd puppet

install:
  # Install Puppet upstream modules
  - ./install-modules.sh

script:
  # Run some Puppet tests
  - ./run-tests.sh
