language: ruby
cache:
  - bundler
  - directories:
    - $HOME/librarian-puppet
gemfile: puppet/Gemfile
env: LIBRARIAN_PUPPET_TMP="$HOME/librarian-puppet"

before_script:
  # All our build steps and tests are for Puppet at the moment
  - cd puppet

script:
  # Install Puppet upstream modules
  - bundle exec ./install-modules.sh
  # Run some Puppet tests
  - bundle exec ./run-tests.sh
