language: ruby
cache: bundler

install:
  - bundle install --jobs=3 --retry=3 --deployment --gemfile=puppet/Gemfile
  # Install Puppet upstream modules
  - (cd puppet && ./install-modules.sh)

script:
  # Run some Puppet tests
  - (cd puppet && ./run-tests.sh)
